services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: tony
      MYSQL_DATABASE: clone_project
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  sales-savvy-app:
    image: sales-savvy-app
    container_name: sales-savvy-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/clone_project
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tony


volumes:
  mysql_data:
  